plugins {
    id 'com.android.application'
}

android {
    // Identidade Jornada E.R. v35
    // Publicacao Jornada E.R. v35
    // Base de assinatura permanente a partir da v32
    namespace 'com.diagnosticoer.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jornadaer.app'
        minSdk 24
        targetSdk 35
        versionCode 35
        versionName '3.0.1-instalacao-limpa'
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("ANDROID_KEYSTORE_PATH")
            if (ksPath) storeFile file(ksPath)
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
}
