plugins {
    id 'com.android.application'
}

android {
    namespace 'com.diagnosticoer.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.diagnosticoer.app'
        minSdk 24
        targetSdk 35
        versionCode 24
        versionName '2.4.2-esgrima-referencia-voz'
    }
}
